project_id = "okxfhhbqxsxtdlneliax"

[functions.send-confirmation-email]
verify_jwt = false

[functions.admin-login]
verify_jwt = false

[functions.set-admin-password]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.chat]
verify_jwt = false
